$(document).ready(function(){
    $("body").prepend("<footer></footer>");
    $("body").prepend("<main></main>");
    $("body").prepend("<header></header>");

    // header

    $("header").append("<nav></nav>");
    $("nav").attr("class","navbar navbar-expand-lg navbar-dark bg-dark fixed-top");
    $("nav").append("<div></div>");
    $("div").attr("class","container");
    $("div").append("<a></a>");
    $("a").attr("class","navbar-brand");
    $("a").attr("href","#");
    $("a").text("Start Bootstrap");
    let divCollaps = $("<div></div>");
    $("div").append(divCollaps);
    divCollaps.attr("class","collapse navbar-collapse");
    divCollaps.append("<ul></ul>");
    $("ul").attr("class","navbar-nav ml-auto");
    let liElement1 = $("<li></li>");
    $("ul").append(liElement1);
    liElement1.attr("class","nav-item active");
    let liElement2 = $("<li></li>");
    $("ul").append(liElement2);
    liElement2.attr("class","nav-item");
    let liElement3 = $("<li></li>");
    $("ul").append(liElement3);
    liElement3.attr("class","nav-item");
    let liElement4 = $("<li></li>");
    $("ul").append(liElement4);
    liElement4.attr("class","nav-item");
    let aelement1 = $("<a></a>");
    liElement1.append(aelement1);
    aelement1.attr("class","nav-link");
    aelement1.attr("href","#");
    aelement1.text("Home");
    let aelement2 = $("<a></a>");
    liElement2.append(aelement2);
    aelement2.attr("class","nav-link");
    aelement2.attr("href","#");
    aelement2.text("About");
    let aelement3 = $("<a></a>");
    liElement3.append(aelement3);
    aelement3.attr("class","nav-link");
    aelement3.attr("href","#");
    aelement3.text("Services");
    let aelement4 = $("<a></a>");
    liElement4.append(aelement4);
    aelement4.attr("class","nav-link");
    aelement4.attr("href","#");
    aelement4.text("Contact");

    // main

    let divcontainer = $("<div></div>");
    $("main").append(divcontainer);
    $(divcontainer).attr("class","container");
    let divRowjumb = $("<div></div>");
    divRowjumb.attr("class","row mt-5 pt-5");
    $(divcontainer).append(divRowjumb);
    let divcol12 = $("<div></div>");
    divcol12.attr("class","col-12");
    $(divRowjumb).append(divcol12);
    let jumbotran = $("<div></div>");
    $(jumbotran).attr("class","jumbotron");
    $(divcol12).append(jumbotran);
    $(jumbotran).append("<h1></h1>");
    $("h1").attr("class","display-3");
    $("h1").text("A Warm Welcome!")
    let pelmentjumb = $("<p></p>");
    $(pelmentjumb).attr("class","lead");
    pelmentjumb.text("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.");
    $(jumbotran).append(pelmentjumb);
    let butonjum = $("<button></button>");
    $(butonjum).attr("type","button");
    $(butonjum).attr("class","btn btn-primary btn-lg");
    $(butonjum).text("Call to action!");
    $(jumbotran).append(butonjum);
    let divRowcard = $("<div></div>");
    $(divRowcard).attr("class","row");
    $(divcontainer).append(divRowcard);
    let divCol3a = $("<div></div>");
    $(divCol3a).attr("class","col-3");
    $(divRowcard).append(divCol3a);
    let divcard1 = $("<div></div>");
    $(divcard1).attr("class","card mb-3");
    $(divCol3a).append(divcard1);
    let image1 = $("<img>");
    $(image1).attr("class","card-img-top");
    $(image1).attr("src","http://placehold.it/500x325");
    $(divcard1).append(image1);
    let divcardbody1 = $("<div></div>");
    $(divcardbody1).attr("class","card-body");
    $(divcard1).append(divcardbody1);
    let h3element1 = $("<h3></h3>");
    $(h3element1).attr("class","card-title text-center");
    $(h3element1).text("Card title");
    $(divcardbody1).append(h3element1);
    let pelement1 = $("<p></p>");
    $(pelement1).attr("class","card-text text-center");
    $(pelement1).text("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.");
    $(divcardbody1).append(pelement1);
    let divcardfooter1 = $("<div></div>");
    $(divcardfooter1).attr("class","card-footer");
    $(divcard1).append(divcardfooter1);
    let divbuton1 = $("<div></div>");
    $(divbuton1).attr("class","text-center");
    $(divcardfooter1).append(divbuton1);
    let butoncard1 = $("<button></button>");
    $(butoncard1).attr("class","btn btn-primary");
    $(butoncard1).text("Find Out More!");
    $(divbuton1).append(butoncard1);
    let divCol3b = $("<div></div>");
    $(divCol3b).attr("class","col-3");
    $(divRowcard).append(divCol3b);
    let divcard2 = $("<div></div>");
    $(divcard2).attr("class","card mb-3");
    $(divCol3b).append(divcard2);
    let image2 = $("<img>");
    $(image2).attr("class","card-img-top");
    $(image2).attr("src","http://placehold.it/500x325");
    $(divcard2).append(image2);
    let divcardbody2 = $("<div></div>");
    $(divcardbody2).attr("class","card-body");
    $(divcard2).append(divcardbody2);
    let h3element2 = $("<h3></h3>");
    $(h3element2).attr("class","card-title text-center");
    $(h3element2).text("Card title");
    $(divcardbody2).append(h3element2);
    let pelement2 = $("<p></p>");
    $(pelement2).attr("class","card-text text-center");
    $(pelement2).text("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.");
    $(divcardbody2).append(pelement2);
    let divcardfooter2 = $("<div></div>");
    $(divcardfooter2).attr("class","card-footer");
    $(divcard2).append(divcardfooter2);
    let divbuton2 = $("<div></div>");
    $(divbuton2).attr("class","text-center");
    $(divcardfooter2).append(divbuton2);
    let butoncard2 = $("<button></button>");
    $(butoncard2).attr("class","btn btn-primary");
    $(butoncard2).text("Find Out More!");
    $(divbuton2).append(butoncard2);
    let divCol3c = $("<div></div>");
    $(divCol3c).attr("class","col-3");
    $(divRowcard).append(divCol3c);
    let divcard3 = $("<div></div>");
    $(divcard3).attr("class","card mb-3");
    $(divCol3c).append(divcard3);
    let image3 = $("<img>");
    $(image3).attr("class","card-img-top");
    $(image3).attr("src","http://placehold.it/500x325");
    $(divcard3).append(image3);
    let divcardbody3 = $("<div></div>");
    $(divcardbody3).attr("class","card-body");
    $(divcard3).append(divcardbody3);
    let h3element3 = $("<h3></h3>");
    $(h3element3).attr("class","card-title text-center");
    $(h3element3).text("Card title");
    $(divcardbody3).append(h3element3);
    let pelement3 = $("<p></p>");
    $(pelement3).attr("class","card-text text-center");
    $(pelement3).text("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.");
    $(divcardbody3).append(pelement3);
    let divcardfooter3 = $("<div></div>");
    $(divcardfooter3).attr("class","card-footer");
    $(divcard3).append(divcardfooter3);
    let divbuton3 = $("<div></div>");
    $(divbuton3).attr("class","text-center");
    $(divcardfooter3).append(divbuton3);
    let butoncard3 = $("<button></button>");
    $(butoncard3).attr("class","btn btn-primary");
    $(butoncard3).text("Find Out More!");
    $(divbuton3).append(butoncard3);
    let divCol3d = $("<div></div>");
    $(divCol3d).attr("class","col-3");
    $(divRowcard).append(divCol3d);
    let divcard4 = $("<div></div>");
    $(divcard4).attr("class","card mb-3");
    $(divCol3d).append(divcard4);
    let image4 = $("<img>");
    $(image4).attr("class","card-img-top");
    $(image4).attr("src","http://placehold.it/500x325");
    $(divcard4).append(image4);
    let divcardbody4 = $("<div></div>");
    $(divcardbody4).attr("class","card-body");
    $(divcard4).append(divcardbody4);
    let h3element4 = $("<h3></h3>");
    $(h3element4).attr("class","card-title text-center");
    $(h3element4).text("Card title");
    $(divcardbody4).append(h3element4);
    let pelement4 = $("<p></p>");
    $(pelement4).attr("class","card-text text-center")
    $(pelement4).text("Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.");
    $(divcardbody4).append(pelement4);
    let divcardfooter4 = $("<div></div>");
    $(divcardfooter4).attr("class","card-footer");
    $(divcard4).append(divcardfooter4);
    let divbuton4 = $("<div></div>");
    $(divbuton4).attr("class","text-center");
    $(divcardfooter4).append(divbuton4);
    let butoncard4 = $("<button></button>");
    $(butoncard4).attr("class","btn btn-primary");
    $(butoncard4).text("Find Out More!");
    $(divbuton4).append(butoncard4);
    
    // footer

    let divfooter = $("<div></div>");
    $(divfooter).attr("class","bg-dark  py-5  text-light")
    $("footer").append(divfooter);
    let pelementfooter = $("<p></p>");
    $(pelementfooter).attr("class","text-center");
    $(pelementfooter).text("Copyright © Your Website 2019");
    $(divfooter).append(pelementfooter);
    
  });
